@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam rectangle<<1>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
rectangle "==Container" <<1>>

skinparam database<<2>> {
  BackgroundColor #f3f4f6
  FontColor #2e3440
  BorderColor #4c566a
}
database "==Container, Database" <<2>>

skinparam rectangle<<3>> {
  BackgroundColor #ffffff
  FontColor #2e3440
  BorderColor #2e3440
}
rectangle "==Container, Server" <<3>>

skinparam rectangle<<4>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
rectangle "==Deployment Node" <<4>>

skinparam rectangle<<5>> {
  BackgroundColor #ffffff
  FontColor #2e3440
  BorderColor #2f855a
}
rectangle "==Deployment Node, Disaster Recovery" <<5>>

skinparam rectangle<<6>> {
  BackgroundColor #ffffff
  FontColor #2e3440
  BorderColor #2b6cb0
}
rectangle "==Deployment Node, Production" <<6>>

rectangle "." <<_transparent>> as 7
7 .[#707070,thickness=2].> 7 : "<color:#707070>Relationship"


@enduml