@startuml
set separator none
title Disaster Recovery Deployment

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<DR.AWS>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC.PublicSubnet.LoadBalancer.AdministrationClient_1>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC.PrivateSubnet.ApplicationTier>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  shadowing false
}
skinparam database<<DR.AWS.VPC.PrivateSubnet.DatabaseTier.Database_1>> {
  BackgroundColor #f3f4f6
  FontColor #2e3440
  BorderColor #4c566a
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC.PrivateSubnet.DatabaseTier>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC.PublicSubnet.LoadBalancer>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC.PrivateSubnet.ApplicationTier.ObsidianCAServer_1>> {
  BackgroundColor #ffffff
  FontColor #2e3440
  BorderColor #2e3440
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC.PrivateSubnet>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC.PublicSubnet>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  shadowing false
}
skinparam rectangle<<DR.AWS.VPC>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
  shadowing false
}

rectangle "AWS\n<size:10>[Deployment Node]</size>" <<DR.AWS>> as DR.AWS {
  rectangle "VPC\n<size:10>[Deployment Node]</size>" <<DR.AWS.VPC>> as DR.AWS.VPC {
    rectangle "Public Subnet\n<size:10>[Deployment Node]</size>" <<DR.AWS.VPC.PublicSubnet>> as DR.AWS.VPC.PublicSubnet {
      rectangle "Load Balancer\n<size:10>[Deployment Node]</size>" <<DR.AWS.VPC.PublicSubnet.LoadBalancer>> as DR.AWS.VPC.PublicSubnet.LoadBalancer {
        rectangle "==Administration Client\n<size:10>[Container: .Net]</size>\n\nProvides the user interface." <<DR.AWS.VPC.PublicSubnet.LoadBalancer.AdministrationClient_1>> as DR.AWS.VPC.PublicSubnet.LoadBalancer.AdministrationClient_1
      }

    }

    rectangle "Private Subnet\n<size:10>[Deployment Node]</size>" <<DR.AWS.VPC.PrivateSubnet>> as DR.AWS.VPC.PrivateSubnet {
      rectangle "Application Tier\n<size:10>[Deployment Node]</size>" <<DR.AWS.VPC.PrivateSubnet.ApplicationTier>> as DR.AWS.VPC.PrivateSubnet.ApplicationTier {
        rectangle "==Obsidian CA Server\n<size:10>[Container: .Net]</size>\n\nProvides Central control" <<DR.AWS.VPC.PrivateSubnet.ApplicationTier.ObsidianCAServer_1>> as DR.AWS.VPC.PrivateSubnet.ApplicationTier.ObsidianCAServer_1
      }

      rectangle "Database Tier\n<size:10>[Deployment Node]</size>" <<DR.AWS.VPC.PrivateSubnet.DatabaseTier>> as DR.AWS.VPC.PrivateSubnet.DatabaseTier {
        database "==Database\n<size:10>[Container: SQL Server]</size>\n\nStores application data." <<DR.AWS.VPC.PrivateSubnet.DatabaseTier.Database_1>> as DR.AWS.VPC.PrivateSubnet.DatabaseTier.Database_1
      }

    }

  }

}

DR.AWS.VPC.PublicSubnet.LoadBalancer.AdministrationClient_1 .[#707070,thickness=2].> DR.AWS.VPC.PrivateSubnet.ApplicationTier.ObsidianCAServer_1 : "<color:#707070>Invokes\n<color:#707070><size:8>[TCP / ASE-protected]</size>"
DR.AWS.VPC.PrivateSubnet.ApplicationTier.ObsidianCAServer_1 .[#707070,thickness=2].> DR.AWS.VPC.PrivateSubnet.DatabaseTier.Database_1 : "<color:#707070>Reads from and writes to\n<color:#707070><size:8>[ODBC]</size>"
@enduml